load("@bazel_rules_cc_module//:tools/cc_module.bzl", "cc_module_library")

cc_module_library(
    name = "mod_a",
    srcs = [
        "partition1.cpp",
        "partition2.cpp",
    ],
    ordered_srcs = ["mod_a.cpp"],
)
